spring:
  application:
    name: user-management
springdoc:
  swagger-ui:
    # Change the default path from /swagger-ui.html
    path: /api-docs-ui.html
    # Sort endpoints alphabetically
    operations-sorter: alpha
  api-docs:
    # Change the path for the raw JSON spec
    path: /v3/api-docs